### ISSUE TITLE
Holy moly this is great!

### ISSUE THREAD

**Issue by playemgames** [forestrf/UnityAnimationWindow#1]
This is not an issue per say but thanks for doing this!  I just posted on the Unity forums complaining that Unity just breaks stuff in the Animation Window and does not fix so I wanted to extend it easily.  The biggest issue I have right now is not being able to search through the Animation Clips in the Animation Window, and I have 1000's of them.  Now there is a bug that I cannot even go through the dreaded drop down menu since it caps off.  Can you lead me to how to change the window to add a search function for the clips attached to the current Animator?  I figured they could just be stored in a Dictionary and then just do a search field using the Keys being the AnimationClip names.  Not sure where to edit though.

**Comment by playemgames** [comment]
I figured it out, thanks for this it was a big help!

**Comment by forestrf** [comment]
Wow. I'm late, sorry.
As you can probably see, I only modified it a bit, cleaned just some small parts and added the buttons. The rest is just code from Unity and an AssemblyDefinition to be able to use the internal namespace. At least now we can fix it ourselves.
Lately I'm only fixing Unity's stuff, it's pretty sad.

**Comment by playemgames** [comment]
No problem!  I ended up not quite forking yours but mixing some of their official code with mine, but yeah I got it to work.  I filed a bug report before because of the 1000 animation limit was breaking the Animation Window drop down.  You can see my edits here:  https://github.com/playemgames/UnityAnimationWindow/blob/master/Assets/Animation%20Window/Editor/AnimationWindow/AnimationWindowClipPopup.cs

**Comment by playemgames** [comment]
This is how I feel as well these days I am forced to just go ahead and try to fix their stuff, they just sit on their hands.  Literally took me about 20 lines of code to fix this and make it easier for people to use.

**Comment by playemgames** [comment]
On problem that will arise though is we will have to edit it when they edit it, otherwise animations and the custom Animation Window may break in future Unity versions.  I just hope they do something when they see this to make fixes on their end.

**Comment by forestrf** [comment]
My fix is also around 20 lines of code, but with an ugly UI (something Unity would not accept). They should be careful if experienced devs keep getting this problems and moving to other engines, I keep being told to move to Unreal, but that editor won't run on my computer anyway.

**Comment by forestrf** [comment]
I made several new changes (you can see them in the commit history, but I added a gif showing them in the readme). I think you will like them :P

**Comment by playemgames** [comment]
Yeah I am looking into Unreal for future projects, as Unity just keeps falling behind the curve and is not stable these days.  Changes look good man!  We should tag team to put in onion skinning, that is one thing I have been bitching at Unity to do for years!
